import turtle

turtle.bgcolor("#000000")
my_pen = turtle.Turtle()
my_pen.color("#ffdd00")
my_pen.begin_fill()
my_pen.color("yellow")
my_pen.circle(80)
my_pen.end_fill()
# Copy begin...
my_pen.goto(-30, 100)
my_pen.color("#000000")
my_pen.begin_fill()
my_pen.circle(10)
my_pen.color("#ffffff")
my_pen.end_fill()
my_pen.pendown()
my_pen.goto(-35, 105)
my_pen.penup()
my_pen.begin_fill()
my_pen.circle(4)
my_pen.color("#000000")
my_pen.end_fill()
my_pen.penup()
my_pen.goto(30, 100)
my_pen.pendown()
my_pen.color("#000000")
my_pen.begin_fill()
my_pen.circle(10)
my_pen.color("#ffffff")
my_pen.end_fill()
my_pen.pendown()
my_pen.goto(35, 105)
my_pen.penup()
my_pen.begin_fill()
my_pen.circle(4)
my_pen.color("#000000")
my_pen.end_fill()
my_pen.penup()
my_pen.goto(0, 25)
my_pen.pendown()
my_pen.begin_fill()
my_pen.color("#000000")
my_pen.circle(15)
my_pen.end_fill()
my_pen.penup()
my_pen.goto(0, 110)
my_pen.pendown()
my_pen.color("Black")
my_pen.pensize(10)
my_pen.setheading(270)
my_pen.forward(40)


turtle.done()